import * as vscode from 'vscode';

const DEFAULT_SETTINGS = JSON.stringify(
  {
    defaultCollection: 'default',
    defaultEnvironment: 'local',
    timeoutMs: 30000,
    followRedirects: true,
    verifyTls: true,
    redactHeaders: ['authorization', 'cookie', 'set-cookie', 'x-api-key'],
  },
  null,
  2,
);

const DEFAULT_COLLECTION = JSON.stringify(
  {
    name: 'Default',
    environments: ['local'],
    requests: [
      {
        id: 'example-get',
        name: 'Default',
        method: 'GET',
        url: '{{baseUrl}}',
        params: [],
        headers: [],
        auth: { type: 'none' },
        body: { type: 'none' },
        docs: 'Example request generated by Pitman.',
      },
    ],
  },
  null,
  2,
);

const DEFAULT_LOCAL_ENV = JSON.stringify(
  {
    name: 'Local',
    variables: { baseUrl: 'http://localhost:8000' },
  },
  null,
  2,
);

const DEFAULT_LOCAL_PRIVATE_ENV = JSON.stringify(
  {
    name: 'Local Private',
    variables: { apiToken: '' },
  },
  null,
  2,
);

const ENV_GITIGNORE = '*.private.env.json\n';
const HISTORY_GITIGNORE = '*\n!.gitignore\n';

async function ensureDir(uri: vscode.Uri): Promise<void> {
  try {
    await vscode.workspace.fs.createDirectory(uri);
  } catch {
    // already exists
  }
}

async function writeIfAbsent(uri: vscode.Uri, content: string): Promise<void> {
  try {
    await vscode.workspace.fs.stat(uri);
  } catch {
    await vscode.workspace.fs.writeFile(uri, Buffer.from(content, 'utf8'));
  }
}

export async function initializePitmanWorkspace(root: vscode.Uri): Promise<void> {
  await ensureDir(root);
  await ensureDir(vscode.Uri.joinPath(root, 'collections'));
  await ensureDir(vscode.Uri.joinPath(root, 'environments'));
  await ensureDir(vscode.Uri.joinPath(root, 'history'));

  await writeIfAbsent(vscode.Uri.joinPath(root, 'settings.json'), DEFAULT_SETTINGS);
  await writeIfAbsent(vscode.Uri.joinPath(root, 'collections', 'default.json'), DEFAULT_COLLECTION);
  await writeIfAbsent(
    vscode.Uri.joinPath(root, 'environments', 'local.env.json'),
    DEFAULT_LOCAL_ENV,
  );
  await writeIfAbsent(
    vscode.Uri.joinPath(root, 'environments', 'local.private.env.json'),
    DEFAULT_LOCAL_PRIVATE_ENV,
  );
  await writeIfAbsent(vscode.Uri.joinPath(root, 'environments', '.gitignore'), ENV_GITIGNORE);
  await writeIfAbsent(vscode.Uri.joinPath(root, 'history', '.gitignore'), HISTORY_GITIGNORE);
}
